version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge